Upgraded to the latest distcc 3.2 Just copied the files from now, it compiles locally but not from the project. Some more work is required to make it compile as stand-alone. It requires libiberty and some warnings to be fixed (which are treated as errors)

diff --git a/distcc/Makefile.in b/distcc/Makefile.in
--- a/distcc/Makefile.in
+++ b/distcc/Makefile.in
@@ -29,6 +29,8 @@ CPP = @CPP@
 CPPFLAGS = @CPPFLAGS@ ${DIR_DEFS} \
 	   -Isrc -I"$(srcdir)/src" -I"$(srcdir)/lzo" $(POPT_INCLUDES)
 
+PYTHON = @PYTHON@
+
 srcdir = @srcdir@
 top_srcdir = @top_srcdir@
 builddir = @builddir@
@@ -56,8 +58,7 @@ include_server_builddir = $(builddir)/_include_server
 
 # These must be done from here, not from autoconf, because they can 
 # contain variable expansions written in Make syntax.  Ew.
-DIR_DEFS = -DSYSCONFDIR="\"${sysconfdir}\"" -DPKGDATADIR="\"${pkgdatadir}\"" \
-           -DPREFIXDIR="\"${prefix}\""
+DIR_DEFS = -DSYSCONFDIR="\"${sysconfdir}\"" -DPKGDATADIR="\"${pkgdatadir}\""
 
 # arguments to pkgconfig
 GNOME_PACKAGES = @GNOME_PACKAGES@
@@ -72,14 +73,6 @@ INSTALL = @INSTALL@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@ 
 INSTALL_DATA = @INSTALL_DATA@
 INSTALL_SCRIPT = @INSTALL_SCRIPT@
-
-# We use python for two tasks in distcc: running the unittests, and
-# running the include-server.  The latter requires python 2.4 or
-# higher, while the former only requires python 2.2.  So it's possible
-# a particular machine will be able to run one but not the other.
-# Thus we have two variables.
-TEST_PYTHON = @TEST_PYTHON@
-INCLUDESERVER_PYTHON = @INCLUDESERVER_PYTHON@
 
 # RESTRICTED_PATH is a colon separated list of directory names.  It
 # contains the locations of 'make', 'sh', 'gcc', and 'python' for use
@@ -119,11 +112,16 @@ dist_files =							\
 
 dist_dirs = m4 include_server/test_data
 
-dist_lzo = lzo/minilzo.c lzo/minilzo.h lzo/lzoconf.h lzo/.stamp-conf.in
+dist_lzo = lzo/minilzo.c \
+	lzo/minilzo.h \
+	lzo/lzoconf.h \
+	lzo/lzodefs.h \
+	lzo/.stamp-conf.in
 
 dist_contrib = contrib/distcc-absolutify	\
 	contrib/distcc.sh		\
 	contrib/distccd-init		\
+	contrib/distccd-on-servers	\
 	contrib/dmake			\
 	contrib/make-j			\
 	contrib/netpwd			\
@@ -152,21 +150,25 @@ pkgdoc_DOCS = AUTHORS COPYING NEWS \
 	TODO \
 	doc/protocol-1.txt doc/status-1.txt \
 	doc/protocol-2.txt \
+	doc/protocol-3.txt doc/protocol-3-impl.txt \
+	doc/protocol-gssapi.txt \
 	doc/reporting-bugs.txt \
 	survey.txt
 
 example_DOCS = \
+	doc/example/README \
+	doc/example/default \
+	doc/example/hosts.allow \
+	doc/example/services \
 	doc/example/init doc/example/init-suse	\
 	doc/example/logrotate				\
 	doc/example/xinetd				\
 
 include_server_PY = \
-	include_server/__init__.py \
 	include_server/basics.py \
 	include_server/cache_basics.py \
 	include_server/compiler_defaults.py \
 	include_server/compress_files.py \
-	include_server/headermap.py \
 	include_server/include_analyzer.py \
 	include_server/include_analyzer_memoizing_node.py \
 	include_server/include_server.py \
@@ -226,8 +228,8 @@ tarball_sig_bz2 = $(tarball_bz2).asc
 tarball_sig_gz = $(tarball_gz).asc
 distnews = $(PACKAGE_TARNAME)-$(VERSION).NEWS
 
-rpm_glob_pattern = "$(PACKAGE)"*[-_.]"$(VERSION)"[-_.]*.deb
-deb_glob_pattern = "$(PACKAGE)"*[-_.]"$(VERSION)"[-_.]*.rpm
+rpm_glob_pattern = "$(PACKAGE)"*[-_.]"$(VERSION)"[-_.]*.rpm
+deb_glob_pattern = "$(PACKAGE)"*[-_.]"$(VERSION)"[-_.]*.deb
 
 common_obj = src/arg.o src/argutil.o					\
 	src/cleanup.o src/compress.o					\
@@ -243,8 +245,7 @@ common_obj = src/arg.o src/argutil.o					\
 	src/implicit.o src/loadfile.o					\
 	lzo/minilzo.o                                                   \
 	@ZEROCONF_COMMON_OBJS@						\
-	@AUTH_COMMON_OBJS@							\
-	@XCODE_INTEGRATION_COMMON_OBJS@					
+	@AUTH_COMMON_OBJS@
 
 distcc_obj = src/backoff.o						\
 	src/climasq.o src/clinet.o src/clirpc.o				\
@@ -255,7 +256,6 @@ distcc_obj = src/backoff.o						\
 	src/timefile.o src/traceenv.o					\
 	src/include_server_if.o						\
 	src/where.o							\
-	@XCODE_INTEGRATION_DISTCC_OBJS@					\
 	@ZEROCONF_DISTCC_OBJS@						\
 	@AUTH_DISTCC_OBJS@						\
 	src/emaillog.o							\
@@ -269,7 +269,6 @@ distccd_obj = src/access.o						\
 	src/serve.o src/setuid.o src/srvnet.o src/srvrpc.o src/state.o	\
 	src/stats.o							\
 	src/fix_debug_info.o						\
-	@XCODE_INTEGRATION_DISTCCD_OBJS@				\
 	@ZEROCONF_DISTCCD_OBJS@						\
 	@AUTH_DISTCCD_OBJS@						\
 	$(common_obj) @BUILD_POPT@
@@ -297,7 +296,6 @@ gnome_obj = src/history.o src/mon-gnome.o				\
 
 h_exten_obj = src/h_exten.o $(common_obj)
 h_issource_obj = src/h_issource.o $(common_obj)
-h_repsubstr_obj = src/h_repsubstr.o $(common_obj)
 h_scanargs_obj = src/h_scanargs.o $(common_obj)
 h_hosts_obj = src/h_hosts.o $(common_obj)
 h_argvtostr_obj = src/h_argvtostr.o $(common_obj)
@@ -320,13 +318,13 @@ SRC =	src/stats.c							\
 	src/backoff.c src/bulk.c					\
 	src/cleanup.c							\
 	src/climasq.c src/clinet.c src/clirpc.c src/compile.c		\
-	src/compress.c src/cpp.c src/cpp_dialect.c				\
+	src/compress.c src/cpp.c					\
 	src/daemon.c src/distcc.c src/dsignal.c				\
 	src/dopt.c src/dparent.c src/exec.c src/filename.c		\
 	src/h_argvtostr.c						\
 	src/h_exten.c src/h_hosts.c src/h_issource.c src/h_parsemask.c	\
 	src/h_sa2str.c src/h_scanargs.c src/h_strip.c			\
-	src/h_dotd.c src/h_compile.c src/h_getline.c h_repsubstr.c                      \
+	src/h_dotd.c src/h_compile.c src/h_getline.c			\
 	src/help.c src/history.c src/hosts.c src/hostfile.c		\
 	src/implicit.c src/io.c						\
 	src/loadfile.c src/lock.c 					\
@@ -346,8 +344,6 @@ SRC =	src/stats.c							\
 	src/dotd.c src/include_server_if.c				\
 	src/emaillog.c							\
 	src/fix_debug_info.c						\
-	src/xci_headermap.c src/xci_utils.c src/xci_versinfo.c		\
-	src/xci_zeroconf.c						\
 	src/zeroconf.c src/zeroconf-reg.c src/gcc-id.c
 
 
@@ -355,7 +351,6 @@ HEADERS = src/stats.h							\
 	src/access.h							\
 	src/auth.h							\
 	src/bulk.h							\
-	src/byte_swapping.h					\
 	src/clinet.h src/compile.h					\
 	src/daemon.h							\
 	src/distcc.h src/dopt.h src/exitcode.h				\
@@ -372,9 +367,8 @@ HEADERS = src/stats.h							\
 	src/exec.h src/lock.h src/where.h src/srvnet.h			\
 	src/rslave.h							\
 	src/dotd.h src/include_server_if.h				\
-	src/emaillog.h							\
-	src/va_copy.h							\
-	src/xci.h							\
+	src/emaillog.h 							\
+	src/va_copy.h 							\
 	src/zeroconf.h
 
 conf_dir = packaging/RedHat/conf
@@ -429,7 +423,6 @@ check_PROGRAMS = \
 	h_fix_debug_info@EXEEXT@ \
 	h_hosts@EXEEXT@ \
 	h_issource@EXEEXT@ \
-	h_repsubstr@EXEEXT@ \
 	h_parsemask@EXEEXT@ \
 	h_sa2str@EXEEXT@ \
 	h_scanargs@EXEEXT@ \
@@ -520,9 +513,6 @@ h_exten@EXEEXT@: $(h_exten_obj)
 h_issource@EXEEXT@: $(h_issource_obj)
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(h_issource_obj) $(LIBS)
 
-h_repsubstr@EXEEXT@: $(h_repsubstr_obj)
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(h_repsubstr_obj) $(LIBS)
-
 h_sa2str@EXEEXT@: $(h_sa2str_obj)
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(h_sa2str_obj) $(LIBS)
 
@@ -581,7 +571,7 @@ distccmon-gnome@EXEEXT@: $(mon_obj) $(gnome_obj)
 # the distcc version, the source location, the CPP flags (for location of the
 # includes), and the build location.
 include-server:
-	if test -z "$(INCLUDESERVER_PYTHON)"; then	\
+	if test -z "$(PYTHON)"; then	\
 	  echo "Not building $@: No suitable python found"; \
 	else						\
 	  mkdir -p "$(include_server_builddir)" &&      \
@@ -589,7 +579,7 @@ include-server:
 	  SRCDIR="$(srcdir)"                            \
 	  CFLAGS="$(CFLAGS) $(PYTHON_CFLAGS)"           \
 	  CPPFLAGS="$(CPPFLAGS)"                        \
-	  $(INCLUDESERVER_PYTHON) "$(srcdir)/include_server/setup.py" \
+	  $(PYTHON) "$(srcdir)/include_server/setup.py" \
 	      build 					\
 	        --build-base="$(include_server_builddir)"  \
 	        --build-temp="$(include_server_builddir)"; \
@@ -714,17 +704,17 @@ TESTDISTCC_OPTS =
 # satisfied w/o actually building an include server (or rather the C extension);
 # this logic needs to be verified or amended.
 maintainer-check-no-set-path:
-	@if ! $(TEST_PYTHON) -c 'import sys; print sys.version'; then \
+	@if ! $(PYTHON) -c 'import sys; print(sys.version)'; then \
 	  echo "WARNING: python not found; tests skipped"; \
 	else \
-	  if ! gcc --version 2>/dev/null; then \
-	    echo "Could not find gcc on the restricted path used to avoid"; \
+	  if ! $(CC) --version 2>/dev/null; then \
+	    echo "Could not find CC on the restricted path used to avoid"; \
 	    echo "confusion caused by distcc masquerades on the normal path."; \
 	    echo "PATH is currently '$$PATH'."; \
 	    echo "Please change RESTRICTED_PATH to change this PATH value."; \
 	    exit 1; \
 	  fi; \
-	  $(TEST_PYTHON) "$(srcdir)/test/testdistcc.py" $(TESTDISTCC_OPTS); \
+	  $(PYTHON) "$(srcdir)/test/testdistcc.py" $(TESTDISTCC_OPTS); \
 	fi
 
 distcc-maintainer-check: check_programs
@@ -747,8 +737,8 @@ include-server-maintainer-check: include-server
 	  for p in $(check_include_server_PY); do \
 	    p_base=`basename "$$p"`; \
 	    echo "Running:" \
-              "PYTHONPATH=$$CURDIR/$$include_server_loc:$$PYTHONPATH $(INCLUDESERVER_PYTHON) $$p_base"; \
-	    if PYTHONPATH="$$CURDIR/$$include_server_loc:$$PYTHONPATH" $(INCLUDESERVER_PYTHON) "$$p_base" \
+              "PYTHONPATH=$$CURDIR/$$include_server_loc:$$PYTHONPATH $(PYTHON) $$p_base"; \
+	    if PYTHONPATH="$$CURDIR/$$include_server_loc:$$PYTHONPATH" $(PYTHON) "$$p_base" \
 		 > "$$CURDIR/$(tempdir)/$$p_base.out" 2>&1; then \
 	      echo "PASS"; \
 	      rm "$$CURDIR/$(tempdir)/$$p_base.out"; \
@@ -776,9 +766,9 @@ maintainer-check: distcc-maintainer-check include-server-maintainer-check \
 	pump-maintainer-check
 
 check:
-	@if test -n "$(INCLUDESERVER_PYTHON)"; then \
+	@if test -n "$(PYTHON)"; then \
 	   $(MAKE) maintainer-check; \
-	elif test -n "$(TEST_PYTHON)"; then \
+	elif test -n "$(PYTHON)"; then \
 	   echo "WARNING: pump-mode not being tested"; \
 	   $(MAKE) distcc-maintainer-check; \
 	else \
@@ -801,7 +791,7 @@ valgrind-check:
 TESTNAME = NoDetachDaemon_Case  # Override this with the desired test.
 single-test: check_programs
 	PATH="`pwd`:$(RESTRICTED_PATH)" \
-	    $(TEST_PYTHON) "$(srcdir)/test/onetest.py" $(TESTDISTCC_OPTS) $(TESTNAME)
+	    $(PYTHON) "$(srcdir)/test/onetest.py" $(TESTDISTCC_OPTS) $(TESTNAME)
 
 # Run a single test in pump-mode.
 pump-single-test: pump include-server check_programs
@@ -864,9 +854,9 @@ maintainer-installcheck: verify-binaries-installcheck distcc-installcheck \
 	pump-installcheck
 
 installcheck:
-	@if test -n "$(INCLUDESERVER_PYTHON)"; then \
+	@if test -n "$(PYTHON)"; then \
 	   $(MAKE) maintainer-installcheck; \
-	elif test -n "$(TEST_PYTHON)"; then \
+	elif test -n "$(PYTHON)"; then \
 	   echo "WARNING: pump-mode not being tested"; \
 	   $(MAKE) distcc-maintainer-installcheck; \
 	else \
@@ -916,7 +906,7 @@ benchmark:
 	@echo "Pass BENCH_ARGS to make to specify which benchmarks to run."
 	@echo
 	@sleep 5
-	cd bench && $(TEST_PYTHON) benchmark.py $(BENCH_ARGS)
+	cd bench && $(PYTHON) benchmark.py $(BENCH_ARGS)
 
 
 ######################################################################
@@ -946,12 +936,12 @@ clean-lzo:
 
 
 clean-include-server:
-	if test -n "$(INCLUDESERVER_PYTHON)"; then	\
+	if test -n "$(PYTHON)"; then	\
 	  DISTCC_VERSION="$(VERSION)"			\
 	  SRCDIR="$(srcdir)"                            \
 	  CFLAGS="$(CFLAGS) $(PYTHON_CFLAGS)"           \
 	  CPPFLAGS="$(CPPFLAGS)"                        \
-	  $(INCLUDESERVER_PYTHON) "$(srcdir)/include_server/setup.py" \
+	  $(PYTHON) "$(srcdir)/include_server/setup.py" \
 	      clean	\
 	         --build-base="$(include_server_builddir)"  \
 	         --build-temp="$(include_server_builddir)"; \
@@ -1065,7 +1055,7 @@ install-programs: $(bin_PROGRAMS)
 # line endings), so we need to convert it from DOS text file format to
 # Unix text file format (LF line endings); we use sed for that too.
 install-include-server: include-server pump
-	if test -z "$(INCLUDESERVER_PYTHON)"; then	\
+	if test -z "$(PYTHON)"; then	\
 	  echo "Not building $@: No suitable python found"; \
 	else						\
 	  mkdir -p "$(include_server_builddir)" &&      \
@@ -1074,7 +1064,7 @@ install-include-server: include-server pump
 	  SRCDIR="$(srcdir)"                            \
 	  CFLAGS="$(CFLAGS) $(PYTHON_CFLAGS)"           \
 	  CPPFLAGS="$(CPPFLAGS)"                        \
-	  $(INCLUDESERVER_PYTHON) "$(srcdir)/include_server/setup.py" \
+	  $(PYTHON) "$(srcdir)/include_server/setup.py" \
 	      build 					\
 	        --build-base="$(include_server_builddir)" \
 	        --build-temp="$(include_server_builddir)" \
